feat(styles): add styles
indec-it/react-form-builder pull request #7
Opened 2018-06-01 12:58 UTC by stellarArg

Order son Components. now every component its a Row > Col. 
Add Styles

2018-06-01 18:06 UTC, navarroaxel requested changes

2018-06-01 18:06 UTC, navarroaxel commented on src/sass/bootstrap/app.scss
> +@import "~bootstrap-sass/assets/stylesheets/bootstrap/variables";
este proyecto no debería tener a bootstrap eso le corresponde a la app que lo usa. se debería poner bootstrap 3.3.7 como `peerDependency` en el `package.json`

2018-06-01 18:08 UTC, navarroaxel submitted a review, later dismissed

2018-06-01 18:08 UTC, navarroaxel commented on src/sass/app.scss
> +.height-component-separation {
semanticamente no me importa que hace el componente sino lo que estiliza debería llamarse `question` si le da la separación a las preguntas.

2018-06-01 18:08 UTC, navarroaxel commented on src/sass/app.scss
> +.disabled {
debería llamarse `question-disabled` si eso es lo q hace.

2018-06-01 19:54 UTC, stellarArg commented on src/sass/bootstrap/app.scss
> +@import "~bootstrap-sass/assets/stylesheets/bootstrap/variables";
ok. Elimino Bootstrap.scss de los imports.

2018-06-01 19:59 UTC, stellarArg commented on src/sass/app.scss
> +.height-component-separation {
Se quito. es algo que era necesario para la muestra del example.

2018-06-01 19:59 UTC, stellarArg commented on src/sass/app.scss
> +.disabled {
Listo.

2018-07-09 22:05 UTC, mdumrauf commented
Meter time-picker.sass en otra carpeta y agregar su respectiva licencia si no se va a tomar de una dependencia directamente (preferible la dependencia).

2018-07-10 21:49 UTC, mdumrauf approved these changes

2018-07-10 21:50 UTC, merged